; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
; sdkconfig: CONFIG_CAMERA_TASK_STACK_SIZE (driver esp32-camera)
board_build.sdkconfig_defaults = sdkconfig.defaults
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCONFIG_ESP32_CAMERA_TASK_STACK_SIZE=32768
    -DCONFIG_CAMERA_TASK_STACK_SIZE=32768
    -DCONFIG_ESP32_CAMERA_TASK_PRIORITY=5
    -DCONFIG_ESP32_DEFAULT_TASK_STACK_SIZE=8192
    -DCONFIG_ESP32_MAIN_TASK_STACK_SIZE=16384
    -DCONFIG_ESP32_TIMER_TASK_STACK_SIZE=8192
board_upload.flash_size = 16MB
upload_port = COM6
upload_speed = 460800
monitor_speed = 115200
monitor_port = COM6
lib_deps = 
    mobizt/FirebaseClient@^2.1.8
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.9
    miguelbalboa/MFRC522@^1.4.11
    adafruit/Adafruit PN532@^1.3.4
